### ISSUE TITLE
String - Nombre Mayus-Minus

### ISSUE THREAD

**Issue by costin132** [costin132/DAM-Entornos-P3-Costin#14]
Una funcion o dos para transformar el nombre todo en mayúsculas y todo en
minúsculas. Como parametro de entrada sera el String y como paramtero de salida el String en mayusculas o minusculas respectivamente.

**Comment by Mel-Gr** [comment]
Funciones añadidas, necesito validacion

**Comment by costin132** [comment]
SI esta bien

**Comment by Mel-Gr** [comment]
Merged
