### ISSUE TITLE
String - Repetir Usuario

### ISSUE THREAD

**Issue by costin132** [costin132/DAM-Entornos-P3-Costin#16]
Funcion para repetir 2 Strings distintos las veces que pida el usuario. Como parametro de entrada es el String 1 y String 2 y como parametro de salida la cantidad de repeticiones pedida por el usuario.

**Comment by Mel-Gr** [comment]
La reabro para que me des tu validacion

**Comment by costin132** [comment]
Si esta bien

**Comment by Mel-Gr** [comment]
Merged
