### ISSUE TITLE
Numero - Tiempo

### ISSUE THREAD

**Issue by costin132** [costin132/DAM-Entornos-P3-Costin#8]
Numero entero positivo como parametro de entrada (int segundos). El parametro de salida 
devolvera  la cadena el total de segundos y los segundos  en horas , minutos  y segundos.

Parametro de entrada: int numero
Parametro de salida:  cadena

**Comment by Mel-Gr** [comment]
La reabro para que me des tu validacion

**Comment by costin132** [comment]
Si esta bien

**Comment by Mel-Gr** [comment]
Merged
